//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebdeNot.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblNote
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> ReminderDate { get; set; }
        public string Description { get; set; }
        public Nullable<int> İmportantyDegree { get; set; }
        public Nullable<bool> Existing { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> WritingDate { get; set; }
    
        public virtual TblUser TblUser { get; set; }
    }
}
